[package]
name = "phantom"
version = "1.2.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
tui = { version = "0.19", default-features = false, features = ['crossterm'] }
ropey = "1.6"
syntect = { version = "5.2", features = ["default-fancy"] }
unicode-width = "0.2"
copypasta = "0.10.1"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
dirs = "6.0"
serde_json = "1.0"
git2 = "0.20"
